from setuptools import setup, find_packages

setup(
    name="cardiac-attr-cm",
    #version="0.1.0",
    author="Yazdan Salimi",
    author_email="salimiyazdan@gmail.com",
    description="a deep learning solution to detect cardiac amyloidosis on scentigraphy images",
    long_description=open('README.md').read(),
    long_description_content_type="text/markdown",
    url="https://github.com/YazdanSalimi/Cardicac-Amyloidosis",
    packages=find_packages(),
    py_modules=["classification", "image-utils", "DL", "attr-cm"],
    install_requires=[
        "pandas",
        "tqdm",
        "termcolor",
        "glob2", 
        "torch",
        "SimpleITK",
        "multiprocess",
        "numpy", 
        "natsort", 
        "batchgenerators",
        "monai", 
        "nibabel",
        "matplotlib",
        "xlsxwriter",
        "openpyxl",
        "pathvalidate",
        "roc-utils",
        "scipy==1.11.4",
    ],
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    python_requires='>=3.6',
)
